version: '3.7'

services:
    klass_database:
        image: postgres:10.5
        restart: always
        environment: 
          - POSTGRES_USER=${POSTGRES_USER:-postgres}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
          - POSTGRES_DB=klass_network
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '5438:5432'